### ISSUE TITLE
- [ ] Create a **Completed** Projects Page

### ISSUE THREAD

**Issue by jon-perez18** [bit-byters/bit-byters-website#3]
Should this be a separate page from "Our Next Byte"? Its currently in there to add more context to the page, but I can always make them two different pages. lmk should be an easy fix.

**Comment by ktapia576** [comment]
Yea a Separate page for the completed projects would be nice I think. It will be a page just about our completed ones or no longer in progress ones. I wanna try to leave our "Our Next Byte" page to just our upcoming projects. 

Unless we name the page differently like "Projects" (instead of "Our next Byte") and the have two "buttons" where one says "Our next byte" and the other says "Completed Projects" to click on to expand the info.
